### PR TITLE
Add support for BDD using Clang

### PR DESCRIPTION
**Pull request by blegat**
I need to use the BDD features of CUDD but this packages seems to only contain the ADD part of CUDD.
This PR adds the whole of CUDD using Clang with a scripts that is added to the `scripts` folder for easy reproducibility.
Would you be ok with replacing the current `ADD_....jl` files with the one generaged by Clang ?

### CODE REVIEW

**Comment by mykelk** [comment]
That's great! I think travis is failing on 0.7. I think we can just drop support for versions of Julia before 1.0. Can you also update the readme file to indicate this support? Thanks!

**Comment by mykelk** [comment]
Also, if you could add to the runtests.jl script, that would be awesome.

**Comment by mykelk** [comment]
Hmm... it looks like there is an issue here, but only on MacOS:
```
BDD: Error During Test at /Users/travis/build/sisl/CUDD.jl/test/runtests.jl:10
  Test threw exception
  Expression: Cudd_bddIsPiVar(manager, v) == -1
  InexactError: trunc(Int32, 140712772398240)
  Stacktrace:
   [1] throw_inexacterror(::Symbol, ::Type{Int32}, ::UInt64) at ./boot.jl:557
   [2] checked_trunc_sint at ./boot.jl:579 [inlined]
   [3] toInt32 at ./boot.jl:621 [inlined]
   [4] Int32 at ./boot.jl:706 [inlined]
   [5] convert at ./pointer.jl:23 [inlined]
   [6] cconvert at ./essentials.jl:390 [inlined]
   [7] Cudd_bddIsPiVar at /Users/travis/build/sisl/CUDD.jl/src/gen/libcudd_api.jl:1794 [inlined]
   [8] macro expansion at /Users/travis/build/sisl/CUDD.jl/test/runtests.jl:10 [inlined]
   [9] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113 [inlined]
   [10] top-level scope at /Users/travis/build/sisl/CUDD.jl/test/runtests.jl:5
```

**Comment by blegat** [comment]
The CI failure on Mac OS with Julia v1.4 is unrelated, it is a network problem

**Comment by mykelk** [comment]
@MaximeBouton this looks good to me. If you're happy can you merge and tag a release?

**Comment by MaximeBouton** [comment]
looks good, I think we don't need all the julia version for travis but I will make the change on master

**Pull request merged**
